#bootstrap and build
before_script: "./script/bootstrap"
script: "./script/cibuild"

#environment
language: ruby
rvm:
  - 2.1.1

branches:
  only:
    - gh-pages
    - /.*/

notifications:
  email: false
